version: '3.8'

services:
  backend:
    container_name: compose-backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: compose-backend
    restart: always
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - backend
      - frontend

  frontend:
    container_name: compose-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: compose-frontend
    restart: always
    ports:
      - 3000:80
    environment:
      - REACT_APP_API_URL=https://aleksr777.nomorepartiesco.ru:3001
    depends_on:
      - backend
    networks:
      - frontend

  database:
    container_name: compose-database
    image: postgres
    restart: always
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - .env
    networks:
      - backend

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - database
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  postgres_data:
