version: '3.9'

services:
  backend:
    container_name: compose-backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: compose-backend
    restart: always
    ports:
      - 4000:4000
    env_file:
      - .env
    networks:
      - backend

  frontend:
    container_name: compose-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: compose-frontend
    restart: always
    ports:
      - 3000:80
    networks:
      - frontend

  postgres:
    container_name: compose-postgres
    restart: always
    image: postgres
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - .env
    networks:
      - backend

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  postgres_data:
